build: 
    build: . 
    command: sh -c 'ls;
                        rm -rf /out/*;
                        git pull --rebase;
                        cd src;
                        make clean;
                        make ${MAKE_TARGET} ${DEBUG_OPTIONS} ${OPTIONS} &&
                        cp -v ${MAKE_TARGET} /out/.'
    volumes: 
        - ./out:/out:rw
        - ./config:/config:ro
    working_dir: /root/ipxe

build-on-docker-machine-fusion: 
    extends:
      service: build
    volumes: 
        - /mnt/hgfs/${PWD}/out:/out:rw
        - /mnt/hgfs/${PWD}/config:/config:ro
